### ISSUE TITLE
Guild Storage Not Updating

### ISSUE THREAD

**Issue by katagatame** [yamdbf/core#12]
There was a specific instance of the guild storage not updating.

The series of events that caused this was:
- Bot was _not_ running
- Bot was removed from one Discord server
- Bot was added/registered to a different Discord server
- Guild storage did not update to include the new Discord server

**Comment by zajrik** [comment]
Happens via the current nature of checking for any changes in guilds when the bot was offline. It simply checks if the number of guilds and number of guild storages are equal and assigns any missing if they are not. But removing from a guild and adding to another when the bot is offline results in an equal number of guilds and storages and the check is not made.

We've already discussed the issue, of course, but I'm just jotting this down further for my own sake. I'll change it to check for storageless guilds and guildless storages every time the bot starts and assign/remove storages appropriately.

**Comment by zajrik** [comment]
Should be fixed in 3689780f835766aa3860fa364fcc16f329402e7f, 2.5.4 release.

Let me know if you encounter any further problems. 👌
