### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by iSypher** [yamdbf/core#16]
Hey, I installed Yamdbf and tried out the example but I get an error message.
```
Error: Cannot find module 'C:/Programming/Github/Node/Core/node_modules/yamdbf/bin/command/base/Eval.js' 
```

Is this a issue with module or am I doing something wrong?

**Comment by zajrik** [comment]
This really isn't enough information to go off of.
- How did you install it? (from NPM or from GitHub?)
- What version of node are you using?
- What version of NPM are you using?
- Have you tried removing your node_modules and reinstalling your dependencies?
- What other dependencies do you have?

Also, this issue may be better suited to being discussed on the official server.

**Comment by iSypher** [comment]
I installed it via yarn and yes I have tried to reinstall it and I have also tried removing node_modules and installing it again. The only dependencies I have is Yamdbf.

Node Version: 8.4.0
NPM Version: 5.3.0

**Comment by zajrik** [comment]
I've never tried installing with Yarn, but I do know that in the past when installing with NPM 5.3.0 there were issues. Try installing NPM 5.0.3 (`npm install -g npm@5.0.3`) and then use NPM to install yamdbf.

I have never had issues getting it to work when installing this way.

**Comment by iSypher** [comment]
I tried what you suggested and it seems I'm still receiving the error.

**Comment by zajrik** [comment]
Can you show me your code and how you are importing YAMDBF? Also, can you confirm whether or not the files it claims to be unable to find are present or not in `node_modules/yamdbf/bin/`?

**Comment by iSypher** [comment]
Here is the code I'm using. 

```javascript
const { Client } = require('yamdbf');
const path = require('path');

class CustomClient extends Client {
  constructor() {
    super({
      token: '',
      readyText: 'Client is ready!',
      commandsDir: './commands',
      pause: true
    });

    this.once('pause', async () => {
      await this.setDefaultSetting('prefix', '-');
      await this.setDefaultSetting('foo', 'bar');
      this.continue();
    });

    this.once('clientReady', () => {
      console.log(`Client ready! Serving ${this.guilds.size} guilds.`);
    });
  }
}

const client = new CustomClient().start();
```

**Eval.js** is in ``bin/command/base/Eval.js'`` but I'm still receiving the error.

**Comment by zajrik** [comment]
Well, the code is all valid, barring not having an actual token but I'm assuming you've left that out for security's sake. I imagine there has to be some issue with how you're installing node modules. No one has ever reported this issue to me before and I cannot replicate the issue.

If you can confirm the file exists in the path that the error says it can't be found and you can confirm that the file contains a valid export, then I cannot think of anything else that I can do to help you with the matter.

**Comment by zajrik** [comment]
I can create a new project, install from npm, and run a test bot in a matter of seconds without issue. I guess all I can recommend at this point is try a installing in a fresh location, make sure you're not installing modules globally, and hope for the best?

**Comment by iSypher** [comment]
Installing in a fresh location solved the issue. Thanks.

**Comment by zajrik** [comment]
Awesome. Glad you could work it out. 👌
